/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperadorIndexRouteImport } from './routes/operador/index'
import { Route as OperadorBuscarRouteImport } from './routes/operador/buscar'
import { Route as OperadorRegistroDniRouteImport } from './routes/operador/registro.$dni'
import { Route as OperadorPersonaVinculoIdRouteImport } from './routes/operador/persona.$vinculoId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorIndexRoute = OperadorIndexRouteImport.update({
  id: '/operador/',
  path: '/operador/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorBuscarRoute = OperadorBuscarRouteImport.update({
  id: '/operador/buscar',
  path: '/operador/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorRegistroDniRoute = OperadorRegistroDniRouteImport.update({
  id: '/operador/registro/$dni',
  path: '/operador/registro/$dni',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorPersonaVinculoIdRoute =
  OperadorPersonaVinculoIdRouteImport.update({
    id: '/operador/persona/$vinculoId',
    path: '/operador/persona/$vinculoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operador/buscar': typeof OperadorBuscarRoute
  '/operador/': typeof OperadorIndexRoute
  '/operador/persona/$vinculoId': typeof OperadorPersonaVinculoIdRoute
  '/operador/registro/$dni': typeof OperadorRegistroDniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operador/buscar': typeof OperadorBuscarRoute
  '/operador': typeof OperadorIndexRoute
  '/operador/persona/$vinculoId': typeof OperadorPersonaVinculoIdRoute
  '/operador/registro/$dni': typeof OperadorRegistroDniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operador/buscar': typeof OperadorBuscarRoute
  '/operador/': typeof OperadorIndexRoute
  '/operador/persona/$vinculoId': typeof OperadorPersonaVinculoIdRoute
  '/operador/registro/$dni': typeof OperadorRegistroDniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/operador/buscar'
    | '/operador/'
    | '/operador/persona/$vinculoId'
    | '/operador/registro/$dni'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/operador/buscar'
    | '/operador'
    | '/operador/persona/$vinculoId'
    | '/operador/registro/$dni'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/operador/buscar'
    | '/operador/'
    | '/operador/persona/$vinculoId'
    | '/operador/registro/$dni'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OperadorBuscarRoute: typeof OperadorBuscarRoute
  OperadorIndexRoute: typeof OperadorIndexRoute
  OperadorPersonaVinculoIdRoute: typeof OperadorPersonaVinculoIdRoute
  OperadorRegistroDniRoute: typeof OperadorRegistroDniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/': {
      id: '/operador/'
      path: '/operador'
      fullPath: '/operador/'
      preLoaderRoute: typeof OperadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/buscar': {
      id: '/operador/buscar'
      path: '/operador/buscar'
      fullPath: '/operador/buscar'
      preLoaderRoute: typeof OperadorBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/registro/$dni': {
      id: '/operador/registro/$dni'
      path: '/operador/registro/$dni'
      fullPath: '/operador/registro/$dni'
      preLoaderRoute: typeof OperadorRegistroDniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/persona/$vinculoId': {
      id: '/operador/persona/$vinculoId'
      path: '/operador/persona/$vinculoId'
      fullPath: '/operador/persona/$vinculoId'
      preLoaderRoute: typeof OperadorPersonaVinculoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OperadorBuscarRoute: OperadorBuscarRoute,
  OperadorIndexRoute: OperadorIndexRoute,
  OperadorPersonaVinculoIdRoute: OperadorPersonaVinculoIdRoute,
  OperadorRegistroDniRoute: OperadorRegistroDniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
